force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Resolved_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Resolved_Accounts__c</fullName>
    <label>Resolved Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Debt_Account__c/Debt_Account__c.object-meta.xml
<CustomObject>
    <label>Debit Account</label>
    <nameField>
        <label>Debit Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debt_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Debit Accounts</relationshipLabel>
    <relationshipName>Debt_Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Debt_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalculateResolvedAccountTest.cls
@istest
public class CalculateResolvedAccountTest{  
    public testMethod static void positivetestmethod(){
        Client__c client = createClient();
        insert client;
        
        List<Debt_Account__c> debitAccountList = new list<Debt_Account__c>();
        debitAccountList = createDebtAccount(3,client);
        insert debitAccountList; 
        
        Client__c objClient = [select Resolved_Accounts__c from Client__c where id =: client.Id];
        System.assertEquals(String.valueOf(objClient.Resolved_Accounts__c),'3');
       
        for(Debt_Account__c objDebitAccount : debitAccountList){
            if(objDebitAccount.Status__c == 'Resolved'){
                objDebitAccount.Status__c ='Active';
            }
        }
        update debitAccountList;
        
        objClient = [select Resolved_Accounts__c from Client__c where id =:client.Id];
        System.assertEquals(String.valueOf(objClient.Resolved_Accounts__c),'0');
    }
    
    private static Client__c createClient(){
        Client__c client1 = new Client__c();
        client1.Name='Client 1';
        client1.Status__c = 'Client';
        return client1;
    }
    
    private static  List<Debt_Account__c> createDebtAccount(Integer numberofAccounts, Client__c client){
        List<Debt_Account__c> debitAccountList = new list<Debt_Account__c>();
        for(Integer i=1;i<=numberofAccounts;i++){
            Debt_Account__c debitAccount= new Debt_Account__c();
            debitAccount.Name = 'TEST ' + i ;
            debitAccount.Status__c ='Resolved';
            debitAccount.client__c = client.ID;
            debitAccountList.add(debitAccount);
        }
        return debitAccountList; 
    }    
}