force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Debt_Account__c/Debt_Account__c.object-meta.xml
<CustomObject>
    <label>Debit Account</label>
    <nameField>
        <label>Debit Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debt_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Debit Accounts</relationshipLabel>
    <relationshipName>Debt_Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Debt_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DebitAccountController.cls
public class DebitAccountController{
    public List<WrapperDebitAccount> wrapperDebitAccounts{get;set;}
    
    public DebitAccountController(){
        wrapperDebitAccounts = new List<WrapperDebitAccount>();
        wrapperDebitAccounts = LoadDebitAccounts();
    }
    
    public List<WrapperDebitAccount> LoadDebitAccounts(){
        List<Debt_Account__c> debitAccountList = new List<Debt_Account__c>();
        List<WrapperDebitAccount> tempWrapperccounts= new List<WrapperDebitAccount>();
         
        debitAccountList = [select id, name,Status__c,Client__r.name,Client__r.Status__c from Debt_Account__c limit 1000];
    
        for(Debt_Account__c account:  debitAccountList){
            tempWrapperccounts.add(new WrapperDebitAccount(account,false));
        }
        return tempWrapperccounts;
    }

    public class WrapperDebitAccount{
        public Boolean isReviewed{get;set;}
        public Debt_Account__c debitAccount{get;set;}

        public WrapperDebitAccount(Debt_Account__c objDebitAccount, boolean bReviewed){
            this.debitAccount = objDebitAccount;
            this.isReviewed = bReviewed;
        }
    }
    
    public pagereference updateReviewed(){
        try{
            List<Debt_Account__c> debitAccountList = new List<Debt_Account__c>();
            
            for(WrapperDebitAccount wp :wrapperDebitAccounts){
                if(wp.isReviewed){
                    Debt_Account__c debt_Account = wp.debitAccount;
                    debt_Account.Reviewed__c=true;
                    debitAccountList.add(debt_Account);  
                }
            }
            
            if(debitAccountList.size()>0){
                update debitAccountList;
                return new pagereference('/apex/DebitAccounts');    
            }
            else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.warning,'Please select at least one record to updates');
                ApexPages.addMessage(myMsg);
                return null;
            }
        }
        catch(exception ex){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getmessage());
            ApexPages.addMessage(myMsg);
            return null;
        }
    }
}